import { createTheme, ThemeProvider } from '@mui/material/styles'
import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Header from '../components/Header'
import Intro from '../components/Intro'
import Categories from '../components/Categories'
import Collections from '../components/Collections'
import BestSellers from '../components/BestSellers'

const Home: NextPage = () => {
  const theme = createTheme({
    palette: {
      primary: {
        main: '#424B25',
      },
      secondary: {
        main: '#F9DE80',
      }
    },
  });

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Piggies Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header theme={theme}/>
        <Intro theme={theme} />
        <Categories theme={theme}/>
        <Collections theme={theme}/>
        <BestSellers theme={theme}/>
      </main>

    </ThemeProvider>
  )
}

export default Home
