import { createTheme, ThemeProvider } from '@mui/material/styles'
import type { NextPage } from 'next'
import Head from 'next/head'
import Header from '../components/Header'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  const theme = createTheme({
    palette: {
      primary: {
        main: '#424B25',
      },
    },
  });

  return (
    <ThemeProvider theme={theme}>
      <Head>
        <title>Piggies Shop</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Header theme={theme}/>
      </main>

    </ThemeProvider>
  )
}

export default Home
